### ISSUE TITLE
Getting exception Failed to generate ID. Underlying exception was: {} when running test case

### ISSUE THREAD

**Issue by vijayrawatsan** [intenthq/icicle#12]
Single tests run perfectly but when all the tests are run it fails saying. @nathankleyn  Can you shed some light?
```java
18:40:56 - Failed to generate ID. Underlying exception was: {}
redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:198) ~[jedis-2.7.3.jar:?]
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40) ~[jedis-2.7.3.jar:?]
	at redis.clients.jedis.Protocol.process(Protocol.java:141) ~[jedis-2.7.3.jar:?]
	at redis.clients.jedis.Protocol.read(Protocol.java:205) ~[jedis-2.7.3.jar:?]
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297) ~[jedis-2.7.3.jar:?]
	at redis.clients.jedis.Connection.getOne(Connection.java:279) ~[jedis-2.7.3.jar:?]
	at redis.clients.jedis.Jedis.getEvalResult(Jedis.java:2642) ~[jedis-2.7.3.jar:?]
	at redis.clients.jedis.Jedis.evalsha(Jedis.java:2668) ~[jedis-2.7.3.jar:?]
	at com.intenthq.icicle.JedisIcicle$2.apply(JedisIcicle.java:85) ~[icicle-jedis-1.1.0.jar:1.1.0]
	at com.intenthq.icicle.JedisIcicle$2.apply(JedisIcicle.java:78) ~[icicle-jedis-1.1.0.jar:1.1.0]
	at com.intenthq.icicle.JedisIcicle.withJedis(JedisIcicle.java:123) ~[icicle-jedis-1.1.0.jar:1.1.0]
	at com.intenthq.icicle.JedisIcicle.evalLuaScript(JedisIcicle.java:78) ~[icicle-jedis-1.1.0.jar:1.1.0]
	at com.intenthq.icicle.IcicleIdGenerator.executeLuaScript(IcicleIdGenerator.java:262) ~[icicle-core-1.1.0.jar:1.1.0]
	at com.intenthq.icicle.IcicleIdGenerator.executeOrLoadLuaScript(IcicleIdGenerator.java:237) ~[icicle-core-1.1.0.jar:1.1.0]
	at com.intenthq.icicle.IcicleIdGenerator.generateIdsUsingRedis(IcicleIdGenerator.java:179) ~[icicle-core-1.1.0.jar:1.1.0]
	at com.intenthq.icicle.IcicleIdGenerator.generateIdBatch(IcicleIdGenerator.java:148) [icicle-core-1.1.0.jar:1.1.0]
	at com.intenthq.icicle.IcicleIdGenerator.generateId(IcicleIdGenerator.java:115) [icicle-core-1.1.0.jar:1.1.0]
```

**Comment by vijayrawatsan** [comment]
May be this is some kind of warning message? As the test case in which this trace appears succesfully passes and have unique ids.

**Comment by vijayrawatsan** [comment]
But output of my test cases turns out to be too ugly.

**Comment by nathankleyn** [comment]
@vijayrawatsan What's happened here is that for some reason Redis has closed one of the workers while running the generation commands. I'm not sure why this is exactly. It may be that your Jedis pool isn't big enough. It could be that you're using a more recent version of Jedis (we're 2.4 currently, although there are plans to upgrade) and it's got an incompatibility with one of the responses.

The ID generation will attempt generation up to 5 times by default. [You can set that number to whatever you want](https://github.com/intenthq/icicle/blob/master/icicle-core/src/main/java/com/intenthq/icicle/IcicleIdGenerator.java#L82-L92). When running tests, you probably want to set it to 1. The message you're seeing is just a warning that a retry took place, there mainly because you'll want to work out the root cause for the retries needing to take place at all (probably one of the above things).

**Comment by vijayrawatsan** [comment]
@nathankleyn when I turned down the retries to just 1, value abset exception pops in.
But after I set up pool size correctly and it worked like a charm.

There is one more issue with your lib. (I hope again that its my own issue). 
I am using your lib in a multi-module maven project. 
Now lets say module2 depends on module1
Both modules are living a happy life before you lib kicks in.
Now module1 depends on icicle. Module1 works and builds just fine.
But spring mongo libraries in module2 are now somehow not working. All the spring-data-mongo imports are in red. 
For the time being I copy pasted your code and it seems to work fine.

**Comment by nathankleyn** [comment]
@vijayrawatsan Sounds like dependency version clashes. Can you [double check the dependencies that Icicle has](https://github.com/intenthq/icicle/blob/2fbccae0aa4996a698d08541785b5b33b56b2e01/build.sbt#L13-L36) and see if any of your modules have conflicting versions? It's probably about time for us to bump some of these versions up to the latest anyway.

**Comment by vijayrawatsan** [comment]
@nathankleyn My common dependencies were already excluded.
```xml
<dependency>
    <groupId>com.intenthq.icicle</groupId>
    <artifactId>icicle-jedis</artifactId>
    <exclusions>
        <exclusion>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </exclusion>
        <exclusion>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by nathankleyn** [comment]
@vijayrawatsan I'm sadly really not sure what the cause could be - I'd expect Icicle to be the one to possibly not work with this setup as the versions that are being used could possibly not be compatible with what Icicle needs. I'm guessing you've checked transient dependencies for clashes as well?

**Comment by vijayrawatsan** [comment]
@nathankleyn I tried figuring out the issue but I couldnot. Plus I didn't check for transient dependencies.
Nevermind its working for me now(by copy pasting the entire library code :disappointed: ). I will try to figure out the exact cause when I have time.

**Comment by nathankleyn** [comment]
@vijayrawatsan :+1:
